alias ni="npm install"
alias nid="npm install --save-dev"
alias nig="npm install -g"
alias nt="npm test"
alias nit="npm install && npm test"
alias nr="npm run"
alias ns="npm start"
alias nff="npm cache clean --force && rm -rf node_modules && npm install"